language: cpp

os: linux
dist: bionic
arch: ppc64le

git:
  depth: false

  quiet: true

branches:
  only: [master]

install:
  - curl -s --compressed "https://raw.githubusercontent.com/friendlyanon/test-cmake-ppa/master/KEY.gpg" | sudo apt-key add -
  - sudo apt-add-repository "deb https://raw.githubusercontent.com/friendlyanon/test-cmake-ppa/master/ ./"
  - sudo apt-get -qq update
  - sudo apt-get purge cmake cmake-data
  - sudo apt-get -y install cmake tree

script:
  - set -e
  - cmake -S . -B build
  - cmake --build build --config Release
  - cd build && ctest -C Release -VV
