language: cpp

os: linux
dist: bionic
arch: ppc64le

git:
  depth: false

  quiet: true

branches:
  only: [master]

install:
  - curl -s --compressed "https://raw.githubusercontent.com/friendlyanon/test-cmake-ppa/master/KEY.gpg" | sudo apt-key add -
  - sudo apt-add-repository "deb https://raw.githubusercontent.com/friendlyanon/test-cmake-ppa/master/ ./"
  - sudo apt-get update -qq
  - sudo apt-get remove cmake cmake-data
  - sudo apt-get install cmake -y

script:
  - cmake --version
