language: cpp

os: linux
dist: bionic
arch: ppc64le

git:
  depth: false
  quiet: true

branches:
  only: [master]

install:
  - wget -q -O - "https://raw.githubusercontent.com/friendlyanon/test-cmake-ppa/master/key.gpg" | sudo apt-key add -
  - sudo apt-add-repository -n "deb https://raw.githubusercontent.com/friendlyanon/test-cmake-ppa/master simdjson main"
  - sudo apt-get update
  - sudo apt-get purge cmake cmake-data
  - sudo ls /var/lib/apt/lists/*_Packages -1 | grep ppa || echo
  - apt-cache policy cmake
  - sudo apt-get -y install tree
  - sudo apt-get -t simdjson -y install cmake

script:
  - set -e
  - cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
  - cmake --build build --config Release
  - cd build && ctest -C Release -VV
